// Permission names, mirrored from backend/src/Auth/Permissions.php. The catalog,
// design rules and endpoint map are docs/PERMISSIONS.md. PermissionsTest (backend)
// fails if this file and the PHP class disagree, so change both together.
//
// The server checks every action itself; these only decide what a screen offers.

export const P = {
  PLATFORM_DASHBOARD_VIEW: 'platform.dashboard.view',
  PLATFORM_PROPERTY_MANAGE: 'platform.property.manage',
  OPERATIONS_TODAY_VIEW: 'operations.today.view',
  OPERATIONS_STAFF_VIEW: 'operations.staff.view',
  FINANCE_COLLECTIONS_VIEW: 'finance.collections.view',
  FINANCE_COLLECTIONS_VIEW_RANGE: 'finance.collections.view_range',
  FINANCE_ANALYTICS_VIEW: 'finance.analytics.view',
  FINANCE_INVOICE_VIEW: 'finance.invoice.view',
  FINANCE_INVOICE_SETTLE: 'finance.invoice.settle',
  FINANCE_INVOICE_REVERSE: 'finance.invoice.reverse',
  FINANCE_RECEIPT_SERIES_MANAGE: 'finance.receipt_series.manage',
  FRONT_DESK_RESERVATION_VIEW: 'front_desk.reservation.view',
  FRONT_DESK_RESERVATION_MANAGE: 'front_desk.reservation.manage',
  FRONT_DESK_RESERVATION_BACKDATE: 'front_desk.reservation.backdate',
  FRONT_DESK_RESERVATION_CORRECT: 'front_desk.reservation.correct',
  FRONT_DESK_RESERVATION_DELETE: 'front_desk.reservation.delete',
  GUESTS_GUEST_VIEW: 'guests.guest.view',
  GUESTS_GUEST_MANAGE: 'guests.guest.manage',
  POS_SALE_VIEW: 'pos.sale.view',
  POS_SALE_MANAGE: 'pos.sale.manage',
  POS_SALE_CANCEL_PAID: 'pos.sale.cancel_paid',
  POS_MENU_MANAGE: 'pos.menu.manage',
  ROOMS_ROOM_VIEW: 'rooms.room.view',
  ROOMS_ROOM_UPDATE_STATUS: 'rooms.room.update_status',
  INVENTORY_ITEM_VIEW: 'inventory.item.view',
  INVENTORY_ITEM_MANAGE: 'inventory.item.manage',
  INVENTORY_CATEGORY_MANAGE: 'inventory.category.manage',
  INVENTORY_STOCK_ADJUST: 'inventory.stock.adjust',
  SETTINGS_PROPERTY_VIEW: 'settings.property.view',
  SETTINGS_CONFIGURATION_VIEW: 'settings.configuration.view',
  SETTINGS_ROOM_MANAGE: 'settings.room.manage',
  SETTINGS_ROOM_RATE_MANAGE: 'settings.room_rate.manage',
  SETTINGS_PROMO_RATE_MANAGE: 'settings.promo_rate.manage',
  SETTINGS_EXTRA_CHARGE_MANAGE: 'settings.extra_charge.manage',
  STAFF_ACCOUNT_VIEW: 'staff.account.view',
  STAFF_ACCOUNT_MANAGE: 'staff.account.manage',
}

// What each stored role holds, for a session whose /auth/me predates
// user.permissions (one release of overlap; remove after that). Same map as
// Permissions::ROLE_GRANTS.
export const ROLE_FALLBACK = {
  owner: [
    P.PLATFORM_DASHBOARD_VIEW,
    P.PLATFORM_PROPERTY_MANAGE,
    P.FINANCE_COLLECTIONS_VIEW,
    P.FINANCE_INVOICE_VIEW,
    P.FINANCE_INVOICE_SETTLE,
    P.FRONT_DESK_RESERVATION_VIEW,
    P.FRONT_DESK_RESERVATION_MANAGE,
    P.GUESTS_GUEST_VIEW,
    P.GUESTS_GUEST_MANAGE,
    P.POS_SALE_VIEW,
    P.POS_SALE_MANAGE,
    P.ROOMS_ROOM_VIEW,
    P.ROOMS_ROOM_UPDATE_STATUS,
    P.INVENTORY_ITEM_VIEW,
    P.SETTINGS_PROPERTY_VIEW,
    P.SETTINGS_CONFIGURATION_VIEW,
    P.FINANCE_COLLECTIONS_VIEW_RANGE,
    P.FINANCE_RECEIPT_SERIES_MANAGE,
    P.POS_SALE_CANCEL_PAID,
    P.POS_MENU_MANAGE,
    P.INVENTORY_ITEM_MANAGE,
    P.INVENTORY_CATEGORY_MANAGE,
    P.INVENTORY_STOCK_ADJUST,
    P.SETTINGS_ROOM_MANAGE,
    P.SETTINGS_ROOM_RATE_MANAGE,
    P.SETTINGS_PROMO_RATE_MANAGE,
    P.SETTINGS_EXTRA_CHARGE_MANAGE,
    P.STAFF_ACCOUNT_VIEW,
    P.STAFF_ACCOUNT_MANAGE,
  ],
  admin: [
    P.FINANCE_COLLECTIONS_VIEW,
    P.FINANCE_INVOICE_VIEW,
    P.FINANCE_INVOICE_SETTLE,
    P.FRONT_DESK_RESERVATION_VIEW,
    P.FRONT_DESK_RESERVATION_MANAGE,
    P.GUESTS_GUEST_VIEW,
    P.GUESTS_GUEST_MANAGE,
    P.POS_SALE_VIEW,
    P.POS_SALE_MANAGE,
    P.ROOMS_ROOM_VIEW,
    P.ROOMS_ROOM_UPDATE_STATUS,
    P.INVENTORY_ITEM_VIEW,
    P.SETTINGS_PROPERTY_VIEW,
    P.SETTINGS_CONFIGURATION_VIEW,
    P.FINANCE_COLLECTIONS_VIEW_RANGE,
    P.FINANCE_RECEIPT_SERIES_MANAGE,
    P.POS_SALE_CANCEL_PAID,
    P.POS_MENU_MANAGE,
    P.INVENTORY_ITEM_MANAGE,
    P.INVENTORY_CATEGORY_MANAGE,
    P.INVENTORY_STOCK_ADJUST,
    P.SETTINGS_ROOM_MANAGE,
    P.SETTINGS_ROOM_RATE_MANAGE,
    P.SETTINGS_PROMO_RATE_MANAGE,
    P.SETTINGS_EXTRA_CHARGE_MANAGE,
    P.STAFF_ACCOUNT_VIEW,
    P.STAFF_ACCOUNT_MANAGE,
    P.OPERATIONS_TODAY_VIEW,
    P.OPERATIONS_STAFF_VIEW,
    P.FINANCE_ANALYTICS_VIEW,
    P.FINANCE_INVOICE_REVERSE,
    P.FRONT_DESK_RESERVATION_BACKDATE,
    P.FRONT_DESK_RESERVATION_CORRECT,
    P.FRONT_DESK_RESERVATION_DELETE,
  ],
  receptionist: [
    P.FINANCE_COLLECTIONS_VIEW,
    P.FINANCE_INVOICE_VIEW,
    P.FINANCE_INVOICE_SETTLE,
    P.FRONT_DESK_RESERVATION_VIEW,
    P.FRONT_DESK_RESERVATION_MANAGE,
    P.GUESTS_GUEST_VIEW,
    P.GUESTS_GUEST_MANAGE,
    P.POS_SALE_VIEW,
    P.POS_SALE_MANAGE,
    P.ROOMS_ROOM_VIEW,
    P.ROOMS_ROOM_UPDATE_STATUS,
    P.INVENTORY_ITEM_VIEW,
    P.SETTINGS_PROPERTY_VIEW,
    P.SETTINGS_CONFIGURATION_VIEW,
    P.OPERATIONS_TODAY_VIEW,
  ],
}
