<?php
declare(strict_types=1);

namespace App\Test\TestCase\Controller\Api;

use Cake\Core\Configure;
use Cake\ORM\Locator\LocatorAwareTrait;
use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

/**
 * Every response carries its request's correlation id (X-Request-Id), so a
 * reported problem can be traced to the events that request wrote. It's
 * always generated by the server.
 */
class CorrelationIdApiTest extends TestCase
{
    use ApiScenarioTrait;
    use IntegrationTestTrait;
    use LocatorAwareTrait;

    private const UUID = '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/';

    private string $token;

    protected function setUp(): void
    {
        parent::setUp();
        $propertyId = $this->createProperty('Correlation Resort');
        $this->token = $this->makeUser($propertyId, 'admin', 'corr-' . uniqid() . '@example.test');
    }

    protected function tearDown(): void
    {
        $this->cleanupScenario();
        parent::tearDown();
    }

    private function requestId(): string
    {
        return $this->_response->getHeaderLine('X-Request-Id');
    }

    public function testSuccessesRefusalsAndErrorsAllCarryAnId(): void
    {
        $this->callAs($this->token, 'GET', '/api/auth/me');
        $this->assertResponseOk();
        $this->assertMatchesRegularExpression(self::UUID, $this->requestId());

        $this->callAs(null, 'GET', '/api/rooms');
        $this->assertResponseCode(401);
        $this->assertMatchesRegularExpression(self::UUID, $this->requestId(), 'on a 401');

        $this->callAs($this->token, 'GET', '/api/guests/999999999');
        $this->assertResponseCode(404);
        $this->assertMatchesRegularExpression(self::UUID, $this->requestId(), 'on a 404');
    }

    public function testEachRequestGetsItsOwnId(): void
    {
        $this->callAs($this->token, 'GET', '/api/auth/me');
        $first = $this->requestId();
        $this->callAs($this->token, 'GET', '/api/auth/me');

        $this->assertNotSame($first, $this->requestId());
    }

    public function testAnIdSentByTheClientIsIgnored(): void
    {
        $this->configRequest(['headers' => [
            'Accept' => 'application/json',
            'Authorization' => 'Bearer ' . $this->token,
            'X-Request-Id' => 'chosen-by-the-caller',
        ]]);
        $this->get('/api/auth/me');

        $this->assertMatchesRegularExpression(self::UUID, $this->requestId());
    }

    public function testTheBrowserMayReadTheId(): void
    {
        Configure::write('debug', true);
        $this->configRequest(['headers' => [
            'Accept' => 'application/json',
            'Authorization' => 'Bearer ' . $this->token,
            'Origin' => 'https://example.test',
        ]]);
        $this->get('/api/auth/me');

        $this->assertSame('X-Request-Id', $this->_response->getHeaderLine('Access-Control-Expose-Headers'));
    }
}
